baseURL = "http://localhost:1313/"
languageCode = 'en-us'
title = 'Shismo Plugins'

[[module.imports]]
path = "github.com/bep/docuapi/v2"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
      unsafe = true

[params]
  search       = true
  maxMenuDepth = 3    # (optional) available options are: 1, 2, or 3 (default: 2)

  # Configure the language example tabs.
  [[params.language_tabs]]
    key  = "java"
    name = "Java"